version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - QuTech-Delft/web-team
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "opensquirrel"
        versions: ["*"]
    reviewers:
      - QuTech-Delft/web-team
      
