name: Nightly SDK build

on:
  schedule:
    - cron: "0 22 * * *"

jobs:
  test:
    name: Integration test with Qiskit dev branch

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Quantum Inspire SDK
      uses: actions/checkout@v4
    - name: Clone Qiskit-terra
      uses: actions/checkout@v4
      with:
        repository: qiskit/qiskit-terra
        path: qiskit-terra
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: pip install prerequisites
      run: pip install --upgrade cython ./qiskit-terra .[dev]
    - name: Run examples
      run: |
        python ./docs/examples/example_qiskit_entangle.py
        python ./docs/examples/example_qiskit_conditional.py
      env:
        QI_TOKEN: ${{ secrets.QI_TOKEN }}
        API_URL: https://api.quantum-inspire.com
    - name: Clean up SDK test projects
      run: |
        python ./docs/examples/delete_projects.py
      env:
        QI_TOKEN: ${{ secrets.QI_TOKEN }}
        API_URL: https://api.quantum-inspire.com
    - name: Clean up pennylane test projects
      run: |
        python ./docs/examples/delete_projects.py
      env:
        QI_TOKEN: ${{ secrets.QI_PENNYLANE_TOKEN }}
        API_URL: https://api.quantum-inspire.com
